server:
  port: 8041

spring:
  application:
    name: cloudalibaba-sentinel-service
  cloud:
    nacos:
      discovery:
        # 配置nacos注册服务中心地址
        server-addr: localhost:8848
      sentinel:
        transport:
          # 配置sendtinel dashboard地址
          dashboard: localhost:8080
          # 默认8719端口，假如被占用会自动从8719开始依次+1扫描，知道找到未被占用的端口
          port: 8719

management:
  endports:
    web:
      exposure:
        include: '*'
